import type { TimelineListItem } from './Timeline';

export const timeline: TimelineListItem[] = [
  {
    from: 'Jan 2023',
    to: 'Sept 2025',
    title: 'Senior Web Developer',
    company: 'FoodByUs',
    description:
      'A business-to-business SaaS platform that streamlines procurement by connecting hospitality venues with wholesale food and beverage suppliers. It centralizes ordering, pricing, and supplier management into a single system, allowing buyers to source ingredients efficiently while enabling suppliers to scale their reach and order volume. FoodByUs effectively removes manual workflows, reduces costs, and provides full visibility across the purchasing lifecycle. More on Frontend-focused development maintaining and developing new features in a pre-existing website.',
    stack: [
      { name: 'Vue', icon: 'vue-icon' },
      { name: 'Node.js', icon: 'nodejs-icon' },
      { name: 'TypeScript', icon: 'typescript-icon' },
      { name: 'MySQL', icon: 'mysql-icon' },
      { name: 'Docker', icon: 'docker-icon' },
      { name: 'ElasticSearch', icon: 'elasticsearch-icon' },
      { name: 'Redis', icon: 'redis-icon' },
      { name: 'PHP', icon: 'php-icon' },
      { name: 'Laravel', icon: 'laravel-icon' },
      { name: 'Figma', icon: 'figma-icon' },
      { name: 'Storybook', icon: 'storybook-icon' },
      { name: 'TailwindCSS', icon: 'tailwindcss-icon' },
      { name: 'Ubuntu', icon: 'ubuntu-icon' },
      { name: 'Nginx', icon: 'nginx-icon' },
    ],
    link: 'https://foodbyus.com',
  },
  {
    from: 'Mar 2022',
    to: 'Dec 2022',
    title: 'Full-Stack Web Developer',
    company: 'Freelance',
    description:
      'Provided end-to-end freelance development support across multiple domains, including assisting a casino operator with licensing and integration of their randomizer application, duplicating and extending casino web platforms for another client with new features that consumed and displayed live sports data, and leading the backend API architecture and admin dashboard development for a taxi service application. These engagements required rapid delivery, cross-functional coordination, and ownership of both technical implementation and solution design.',
    stack: [
      // leggo
      { name: 'PHP', icon: 'php-icon' },
      { name: 'Laravel', icon: 'laravel-icon' },
      { name: 'Redis', icon: 'redis-icon' },
      { name: 'GCP', icon: 'gcp-icon' },
      { name: 'MySQL', icon: 'mysql-icon' },
      { name: 'Docker', icon: 'docker-icon' },
      { name: 'Vue', icon: 'vue-icon' },
      { name: 'TailwindCSS', icon: 'tailwind-icon' },
      { name: '/', icon: '' },
      // groundlink
      { name: 'PHP', icon: 'php-icon' },
      { name: 'Node.js', icon: 'nodejs-icon' },
      { name: 'JavaScript', icon: 'javascript-icon' },
      { name: 'jQuery', icon: 'jquery-icon' },
      { name: 'MySQL', icon: 'mysql-icon' },
      { name: 'WebSocket', icon: '' },
      { name: '/', icon: '' },
      // casino
      { name: 'Node.js', icon: 'nodejs-icon' },
      { name: 'NestJS', icon: 'nestjs-icon' },
      { name: 'TypeScript', icon: 'typescript-icon' },
      { name: 'Redis', icon: 'redis-icon' },
      { name: 'MySQL', icon: 'mysql-icon' },
      { name: 'Microservices', icon: '' },
      { name: 'PostgreSQL', icon: 'postgresql-icon' },
    ],
  },
  {
    from: 'Aug 2019',
    to: 'Sept 2021',
    title: 'Web Developer -- Senior Web Developer',
    company: 'Vavasoftware',
    description:
      'Integrated third-party casino game providers into an existing gaming platform while leading the support team responsible for rapid hotfix deployment and production issue resolution. Additionally, implemented the end-to-end integration of live sports data services, ensuring real-time accuracy, stability, and seamless functionality across the platform.',
    stack: [
      { name: 'PHP', icon: 'php-icon' },
      { name: 'Laravel', icon: 'laravel-icon' },
      { name: 'Vue', icon: 'vue-icon' },
      { name: 'MySQL', icon: 'mysql-icon' },
      { name: 'VirtualBox', icon: 'virtualbox-icon' },
      { name: 'CentOS', icon: 'centos-icon' },
      { name: 'Ubuntu', icon: 'ubuntu-icon' },
      { name: 'Node.js', icon: 'nodejs-icon' },
      { name: 'JavaScript', icon: 'javascript-icon' },
      { name: 'jQuery', icon: 'jquery-icon' },
      { name: 'WebSocket', icon: '' },
      { name: 'CSS3', icon: 'css3-icon' },
      { name: 'Apache', icon: 'apache-icon' },
      { name: 'Nginx', icon: 'nginx-icon' },
    ],
  },
  {
    from: 'Feb 2018',
    to: 'Aug 2019',
    title: 'Associate Web Developer -- Software Engineer',
    company: 'MFT Group of Companies',
    description:
      'Maintained and enhanced a pre-existing stock trading platform by integrating real-time market price data into the remote server infrastructure and leading a comprehensive UI revamp to improve usability, performance, and visual clarity. This work required deep familiarity with data feeds, responsive design, and production-level system maintenance to ensure a stable and intuitive trading experience.',
    stack: [
      { name: 'Python', icon: 'python-icon' },
      { name: 'Django', icon: 'django-icon' },
      { name: 'JavaScript', icon: 'javascript-icon' },
      { name: 'CSS3', icon: 'css3-icon' },
      { name: 'jQuery', icon: 'jquery-icon' },
      { name: 'Vagrant', icon: 'vagrant-icon' },
      { name: 'Ubuntu', icon: 'ubuntu-icon' },
      { name: 'PostgreSQL', icon: 'postgresql-icon' },
      { name: 'WebSocket', icon: '' },
    ],
    link: 'https://mftgroup.com.ph/',
  },
  {
    from: 'Aug 2017',
    to: 'Nov 2017',
    title: 'Trainee',
    company: 'Zuitt Coding Bootcamp',
    description:
      'Completed an intensive web development bootcamp that established a solid foundation in PHP, MySQL, HTML, CSS, Bootstrap, and Laravel. The program emphasized practical, project-based learning, enabling me to build full-stack applications, understand core backend and frontend concepts, and develop the technical discipline that shaped the early stages of my web development career.',
    stack: [
      { name: 'HTML5', icon: 'html5-icon' },
      { name: 'CSS3', icon: 'css3-icon' },
      { name: 'JavaScript', icon: 'javascript-icon' },
      { name: 'jQuery', icon: 'jquery-icon' },
      { name: 'PHP', icon: 'php-icon' },
      { name: 'MySQL', icon: 'mysql-icon' },
      { name: 'Laravel', icon: 'laravel-icon' },
    ],
    link: 'https://john-dunglao-dev.github.io/developer-ako/',
  },
];
